---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-app
  namespace: insecure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      containers:
      - image: confusedcrib/insecure-app:latest
        name: insecure-app
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
      serviceAccountName: insecure-app-sa
---
kind: Service
apiVersion: v1
metadata:
  name: insecure-app
  namespace: insecure-app
spec:
  type: ClusterIP
  selector:
    app: insecure-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: insecure-app-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: insecure-app-role-binding
subjects:
- kind: ServiceAccount
  name: insecure-app-sa
  namespace: insecure-app
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: insecure-app-role
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: insecure-app-sa
  namespace: insecure-app